### ISSUE TITLE
BTS?

### ISSUE THREAD

**Issue by sasdom919** [TeamSpen210/tspenAddons#29]
Not much of issue than question: Is there going to be behind the scenes theme with the outside of chambers and the arms holding them? I'd like to try it but I cannot even find this style

**Comment by TeamSpen210** [comment]
If you look in the BTS-style branch there's an incomplete version of this. First I've got to release the BEE2.4, which involves basically remaking a lot of the current styles to take advantage of new features. The BTS style will probably be the next new one though.

**Comment by sasdom919** [comment]
It would be cool if there was at least Wheatley style with open space generated with an element, oh well can't explain what I mean since...i'm not very sure...how to say it..

**Comment by TeamSpen210** [comment]
The Wheatley Destroyed, BTS, and Art Therapy styles will have skybox-based bottomless pits instead of goo pits. The code behind that isn't really ready yet though. 

The refurbished style is partially based on the last coop course, where GLaDOS injects some modern elements into the puzzle to allow you to actually complete it. There's nothing above that tube, other than a pitch-black wall. If you were to see up there I'd imagine it'd look like the modern BTS / Art-therapy exterior areas, with an enrichment sphere hauled up on massive cranes or something like that.

**Comment by sasdom919** [comment]
Also for wheatley style, I only mean wheatley monitors. If we look the element "Wheatley Monitor" instantly it's name says it's made by Wheatley, anyways you planning dates for Wheatley Style?

**Comment by TeamSpen210** [comment]
The Wheatley Monitor needs a name change, since it can change appearance a lot depending on the style.

**Comment by sasdom919** [comment]
I've got a suggestion for ending map without elevator
Like in BTS styles

**Comment by sasdom919** [comment]
Ok well seriously if you can make your own properties menu, It'll be cool if you can make subtitle text like on some maps saying Thanks for playing or such (something similar to trigger)

**Comment by sasdom919** [comment]
Also, I think a addition of ability to select elevator room screen video (Lasers, Jumppads/Faith Plates, BSoD etc)
(It should have been within PeTI even without this mod. If you use mainly a specified element like lasers, it'll talk about it

**Comment by TeamSpen210** [comment]
I need to remake the catwalks, and their editor models. I'm planning on having 2 Wheatley Styles - "Clean", which has no destroyed/BTS elements (but with goo), and "Destroyed", with lots of BTS visible. 

You can download most of the stuff I've made so far, choose a branch and download a zip on the right-hand sidebar here on GitHub. A lot of the stuff is tied up with the new BEE2 revamp, and is instead at [BEE2.4](https://github.com/BenVlodgi/BEE2.4) and [BEE2-items](https://github.com/TeamSpen210/BEE2-items).

The PeTI isn't really meant for multi-chamber map series, and the elevators are very tightly interconnected into the styles. I don't think an elevator selector would work too well. The BTS styles will have non-elevator exits/entries (catwalks, offices, or factory themed).

There won't be cores, or anything like that. They have absolutely no business in a chamber, and really only work if you have Hammer's freedom to script them and add dialogue. The PeTI isn't for storylines, it just doesn't work very well.

I can't make an item with editable text. Valve has that item in the education version of Portal 2, but it requires special code in that game version. It wouldn't work in the regular Portal 2 (I wish we had those items though, some could be quite useful.)

I think I'll add an elevator video selector, though. That is pretty common in many styles.

**Comment by sasdom919** [comment]
Not much I mean about ending outside elevator but making it possible to fadein and teleport to the box where it auto-teleports player it's possible to noclip to see it (in usual game, it changes to next chamber)
Similar to how bts maps are like

**Comment by sasdom919** [comment]
However, Portal 2 Educational Version uses almost the same code as Portal 2...
..can't it be possible to make the text bubble (and maybe contraption cubes)?

**Comment by sasdom919** [comment]
Please reply:
What about choice of Map Loading Screens?
There are some: Reconstructing (The one with 2 lasers and moving panels), Burning (SP_A3_00), Wheatley (the one with frankenturret)
And text only:
Aperture Science Innovators (1950s logo)
Aperture (The first map after you get potatOS)
Aperture Laboratories (Clean version, as in The Cold Boot's end)
Overgrown Aperture (Aperture Laboratories, dirty version)
Wheatley Laboratories (The ITCH)

Maybe as bonus: Aperture Fixtures?
And maybe the concept logo?

**Comment by TeamSpen210** [comment]
This can't be done. Using the loading screens requires the map to be named a certain name, which would stop Portal 2 from being able to find the file to publish it.

**Comment by sasdom919** [comment]
Oh ok. I didn't know. Well, what about the commentary nodes? We can give it a try?

**Comment by sasdom919** [comment]
Well, here it is: What about these arrows that Ratman has been drawing? Can they be used?

**Comment by TeamSpen210** [comment]
I can use those easily. They probably won't appear in the BEE2 much, though since Ratmann mainly puts drawings in the nooks and crannies behind the testchamber walls, which you don't see too much.

**Comment by sasdom919** [comment]
Ok then, what about the sliding doors and observation rooms with broken glass and way to get in?
And about the rattman, ignore but: Do you plan actually to work on elevator screens? And also can you add direction of start elevator and finish elevator? And like wheatley: He uses random speed of elevator, maybe we could use custom too?

**Comment by TeamSpen210** [comment]
The BTS style will use those sliding doors and corridors 50% of the time for the entry/exit rooms. I won't want to add accessible observation rooms, the extra portal surface could allow players to cheat the puzzle. I'm going to add an elevator chooser  to the BEE2 UI so you can choose exactly which elevator video is used, including choosing some videos that aren't normally used as elevator videos. I don't think I'll add elevator direction choosing right now, but maybe in the future.

**Comment by sasdom919** [comment]
Wait, so we have to reset portal 2 everytime we want to change the elevator screen?
Also: What about Reconstructing Style (Overgrown after GLaDOS has been awaken but still haven't cleaned all chambers.

**Comment by TeamSpen210** [comment]
Most of the setting types you can customise rely on the custom compiler to make the changes, and so you don't need a restart. (The main exceptions are items and styles). Just Alt-Tab back to Portal 2, re-export, and it'll apply fine. In the current BEE2, changing the style while Portal 2 is open will change all the textures, but it'll still use the old instances and editor data.

I'm currently thinking I'll actually make 2 reconstructing styles - one with heavily damaged chambers, and one which is almost entirely clean. Since voice lines and styles are being separated, I'll probably actually release a bunch of voice packs ahead of the actual styles.

**Comment by sasdom919** [comment]
You mean, that I don't need to reset my Portal 2 when i'm changing only the style and elevator video?

**Comment by TeamSpen210** [comment]
When changing style or the item layout you will need to restart, but elevator screens, skybox, music, goo, voice lines and some others will function perfectly. All the Style Properties check boxes will function too without restarts.

You'll also be able to change some other settings, like what screenshot will be uploaded.

**Comment by sasdom919** [comment]
Atall, is there planned date to start developing the elevator screens? Or you started already?

**Comment by TeamSpen210** [comment]
I was literally just [working on that][commit]. The option doesn't do anything, but it reads in the elevator video options from packages.

I don't really want to encourage "secret" things in the PeTI, since that's one easy way to create a really frustrating puzzle. That's probably one of the reasons why the editor originally didn't have Antlines connection visibility options. That's also why there's glass in my Retractable Pedestal Button, and 50s Retractable Floor Buttons, so you know there's a button there. 

[commit]: https://github.com/BenVlodgi/BEE2.4/commit/31a17218cce2490f592d6a6bf6c6779c44076126

**Comment by sasdom919** [comment]
Wait: Since my maps im working on are supposed to include only and only BTS doors, and I want to make custom chamber signs that should work even in preview

**Comment by sasdom919** [comment]
Last post here: Also when you fix catwalks, make them work on air too please

**Comment by TeamSpen210** [comment]
I need to figure out a way to solve that. Except for cubes, all items must be attached to a surface. Maybe I can do something special with the compiler, so the catwalk auto-generates between corner-pieces.

**Comment by Bruce6131** [comment]
I can't find BTS style in BEE2 do I have to download a package?

**Comment by Wehttam04** [comment]
where can I find the BTS style package or what ever I need

**Comment by vrad-exe** [comment]
Please don't use this issue to ask for BTS style to be added back
