### ISSUE TITLE
Port items to latest version

### ISSUE THREAD

**Issue by TristanBomb** [TeamSpen210/tspenAddons#34]
I noticed several of the items in this repo haven't been ported yet to 2.4, such as the world portals. Any chance of this happening?

**Comment by TeamSpen210** [comment]
Yes, I'm working on it (TeamSpen210/BEE2-items#95).

**Comment by TristanBomb** [comment]
My bad. Didn't see that issue! Thank you for all your hard work on making Portal 2 puzzles so much better :(
